version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.8.1
  aws-ecs: circleci/aws-ecs@1.1.0

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
            repo: "${AWS_ECR_REPO}"
            region: AWS_REGION
            tag: latest
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image # only run this job once aws-ecr/build_and_push_image has completed
          family: "${AWS_ECS_SERVICE}"
          cluster-name: "${AWS_CLUSTER_NAME}"
          container-image-name-updates: "container=${AWS_ECR_REPO}-service,tag=${CIRCLE_SHA1}"