version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.8.1
  aws-ecs: circleci/aws-ecs@1.1.0

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
            repo: $AWS_ECR_REPO
            region: AWS_REGION
      - aws-ecs/update-task-definition-from-json:
          requires:
            - aws-ecr/build-and-push-image
          task-definition-json: task-definition.json
      - aws-ecs/deploy-service-update:
          requires:
            - update-task-definition-from-json
          family: $AWS_ECS_SERVICE
          cluster-name: $AWS_CLUSTER_NAME
          container-image-name-updates: "container=application,image-and-tag=${AWS_ECR_ACCOUNT_URL}/${AWS_ECR_REPO}:latest"